node {
    stage('Checkout') {
      git url: 'https://github.com/rhashmi02/final-project.git'
    }

    stage('Gradle build') {
      dir('/rest-server') {
        bat 'gradle build'
      }
    }
}
