node {
    stage('Checkout') {
      git branch: 'main', url: 'https://github.com/rhashmi02/final-project.git'
    }

    stage('Gradle build') {
      dir('rest-server') {
        
        sh 'gradle build'
      }
    }
}
